import { createSlice } from "@reduxjs/toolkit";

// define the initial state and reducers in a slice
const CounterSlice = createSlice({
    name: "Counter",
    initialState: { value: 10 },
    reducers: {
        increment: (state) => {
            state.value += 1   //mutating code
        },
        decrement: (state) => {
            state.value -= 1     //mutating code
        }
    }
})

//export the action creators generated by createslice
export const { increment, decrement } = CounterSlice.actions;

//export the reducer to be used in the store
export default CounterSlice.reducer;